// Import which is generated by a loader which uses a file glob in the resolve.modules folders.
require('./generated?type=magic');

const getMessage = require('package1/src/getMessage.js');
import getMessageEsm from 'package1/src/getMessageEsm.js';

console.warn(getMessage());
console.warn(getMessageEsm());
